// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team2377.robot.subsystems;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORT
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.Subsystem;

public class FmsSubSystem extends Subsystem {
	@Override
    public void initDefaultCommand() {
       
    }
 	
 	// Put methods for controlling this subsystem
    // here. Call these from Commands.
	/**
	 * Checks to see if the Right side of the scale is our color.
	 * @param fieldLayout - layout from FMS
	 * @return - True(Right side of scale is our color) otherwise false
	 */
    public static boolean getRightScaleActive (String fieldLayout) {
    	if(fieldLayout.charAt(1) == 'R')
    	{
    		return true;
    	}
    	else
    	{
    		return false;
    	}
    	
    }

    public static boolean getRightSwitchActive (String fieldLayout) {
    	System.out.println("Entering RSA: " + fieldLayout);
    	if(fieldLayout.charAt(0) == 'R')
    	{
    		return true;
    	}
    	else
    	{
    		return false;
    	}
    	
    }
    
    /**
     * Get the field configuration from the FMS
     * @return - String of length 3 populated with L and R.  Possibly null
     */
    public static String getSwitchAndScaleLayout() {
    	return DriverStation.getInstance().getGameSpecificMessage();
    }
   
}

