package org.usfirst.frc.team2377.robot.commands;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.CommandGroup;

import java.time.LocalDateTime;

import org.usfirst.frc.team2377.robot.Robot;
import org.usfirst.frc.team2377.robot.subsystems.*;

public class CenterSwitch extends CommandGroup {
	//private double m_distance = 0;
	private Logging logger;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATION

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public CenterSwitch() {
    	logger.init("CenterSwitch");
    	System.out.println("Entering center switch code, " + FmsSubSystem.getRightSwitchActive(Robot.switchScaleLayout));
    	if(FmsSubSystem.getRightSwitchActive(Robot.switchScaleLayout))
    	{
    		logger.info("The robot is going to the right switch", LocalDateTime.now());
    	addSequential(new DriveForward(Robot.autonLine , .6 ));
    //	addSequential(new PlaceBlock( some thingy that we will put in here based off manipulator mechanics));
    	}
    	else
    	{
    		logger.info("The robot is going to the left switch", LocalDateTime.now());
    		addSequential(new AutoOpenCloseGripper(true));//close
        	addSequential(new DriveForward(Robot.C2LSw_Leg_1, .6 ));
        	addSequential(new AutoRotateLeft(Robot.RotateLeft,  .6));
        	addSequential(new DriveForward(Robot.C2LSw_Leg_2, .6 ));
        	addSequential(new AutoRotateRight(Robot.RotateRight,  .6 ));
        	// raise elevator
        	addSequential(new DriveForward(Robot.C2LSw_Leg_3, .6 ));
    		addSequential(new AutoOpenCloseGripper(false));//open
    	}
    	logger.close();
    		
    		
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
}
