package org.usfirst.frc.team2377.robot.commands;

import org.usfirst.frc.team2377.robot.Robot;
import org.usfirst.frc.team2377.robot.subsystems.FmsSubSystem;
import org.usfirst.frc.team2377.robot.subsystems.Logging;

import edu.wpi.first.wpilibj.command.CommandGroup;

public class LeftPositionBothScales extends CommandGroup {
	// private double m_distance = 0;
	private Logging logger;
	private double elevator_speed = .8;
	private double drive_speed = .7;
	private double turn_speed = .5;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATION

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	public LeftPositionBothScales() {
		// logger.init("Only Scale");
		System.out.println("Entering scale only code, " + FmsSubSystem.getRightSwitchActive(Robot.switchScaleLayout));
		if (FmsSubSystem.getRightScaleActive(Robot.switchScaleLayout)) {
			// TODO get preferences for new mode
			// logger.info("The robot is going to the right switch", LocalDateTime.now());
			addSequential(new AutoOpenCloseGripper(true));// close
			addSequential(new AutoRotateArmOut());// out
			addSequential(new DriveForward(Robot.L2RSc_Leg_1, .8));
			addSequential(new AutoRotateRight(Robot.RotateRight, .6));
			addSequential(new DriveForward(Robot.L2RSc_Leg_2, .8));
			addSequential(new AutoRotateLeft(Robot.RotateLeft, .6));
			addSequential(new AutoMoveElevator(Robot.RaiseElevatorSc, .8, 2));
			addSequential(new DriveForward(Robot.L2RSc_Leg_3, .8));
			// addSequential(new AutoRotateLeft(Robot.RotateLeft, .6));
			// addSequential(new AutoMoveElevator(Robot.RaiseElevatorSc, .6, 2));
			// addSequential(new DriveForward(Robot.L2RSc_Leg_4, .35));// maybe not needed
			// addSequential(new AutoOpenCloseGripper(false));// maybe not needed
			addSequential(new AutoOutputDriveShooterWheels(.40));
		} else {
			// logger.info("The robot is going to the left scale.", LocalDateTime.now());
			addSequential(new LeftPositionToLeftScale(false, false));
		}
		// logger.close();

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}
}
