// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc.team2377.robot.commands;

import org.usfirst.frc.team2377.robot.Robot;
import org.usfirst.frc.team2377.robot.RobotMap;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class driveWithJoystick extends Command {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	public driveWithJoystick() {

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		System.out.println("Got to the requires in drivewithjoysticks");
		requires(Robot.driveSystem);
		System.out.println("Got to the requires in drivewithjoysticks");

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}

	// Called just before this Command runs the first time
	@Override
	protected void initialize() {

		System.out.println("Running Drive with Joysticks");
	}

	// Called repeatedly when this Command is scheduled to run
	@Override
	protected void execute() {
		if (Robot.oi.halfSpeed.get()) {
			RobotMap.driveSystemRobotDrive21.tankDrive(Robot.oi.getDriverLeftDriveValue() * .65,
					Robot.oi.getDriverRightDriveValue() * .65);
			RobotMap.driveSystemRobotDrive41.tankDrive(Robot.oi.getDriverLeftDriveValue() * .65,
					Robot.oi.getDriverRightDriveValue() * .65);
		}

		else {
			RobotMap.driveSystemRobotDrive21.tankDrive(Robot.oi.getDriverLeftDriveValue(),
					Robot.oi.getDriverRightDriveValue());
			RobotMap.driveSystemRobotDrive41.tankDrive(Robot.oi.getDriverLeftDriveValue(),
					Robot.oi.getDriverRightDriveValue());
		}
	}

	// Make this return true when this Command no longer needs to run execute()
	@Override
	protected boolean isFinished() {
		return false;
	}

	// Called once after isFinished returns true
	@Override
	protected void end() {
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	@Override
	protected void interrupted() {
	}
}
